### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by boeserwolf** [halfnelson/svelte-native#148]
It would be great to have access to the classes `.ns-light` and `.ns-dark` to determine whether the dark mode is enabled or not. 

> Since version 6.2, NativeScript detects the system appearance of the running mobile operating system and applies a respective CSS class to the application's root view. In particular, if you run the application on iOS 13.0 in Light mode, a .ns-light CSS class will be assign to the root view of your application. In analogy, if you change the system appearance from Light to Dark, the .ns-light class will be replaced with .ns-dark and vice versa.

Ref.: https://docs.nativescript.org/ui/dark-mode

```css
.ns-light Page {
    background-color: lightblue;
}

.ns-dark Page {
    background-color: darkblue;
}
```

Workaround to detect dark mode on iOS:

```js
import { topmost } from "tns-core-modules/ui/frame";
const isDarkModeEnabled = topmost().viewController.traitCollection.userInterfaceStyle === 2;
```

**Comment by boeserwolf** [comment]
Closed. It works using the :global scope like so:
```css
:global(.ns-light) page { 
  background-color: yellow;
}
```
